### ISSUE TITLE
Custom image

### ISSUE THREAD

**Issue by null15** [gabe7384/DTM-16-Revamp#1]
Hi, would it be possible for me to use a custom image? Also I noticed a problem with server images
![image](https://user-images.githubusercontent.com/30800470/112314819-c2c53d80-8ca9-11eb-8945-ecdbadc35850.png)

And discord logo:
![image](https://user-images.githubusercontent.com/30800470/112314842-c8bb1e80-8ca9-11eb-9185-b459fa3f9e0b.png)

**Comment by gabe7384** [comment]
Are you sure you dont have any other css that could mess up the discord logo? And with the server images that is a problem with all DTM-16 themes and havent quite come up with a fix I will be working on it but cant guarantee custom images there.
